#80的测试的好处是  默认就是是用的80端口  不用在地址名后面添加端口号了
server:
  port: 80

eureka:
  client:
    #表示是否默认将自己入驻进eureka注册服务中心
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册中心，默认为true。单节点无所谓，集群必须配合ribbon使用负载均衡
    fetch-registry: true
    #入驻eureka服务器的地址
    service-url:
#      defaultZone: http://eureka01.com:7001/eureka
      defaultZone: http://eureka02.com:7002/eureka,http://eureka01.com:7001/eureka  #集群版

spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.98.101.65:3306/springCloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml